const properties = [
  {
    id: "3958dc9e-712f-4377-85e9-fec4b6a6442a",
    type: "Villa",
    name: "Seaside Serenity Villa",
    href: "/properties/seaside-serenity-villa",
    description:
      "A stunning 4-bedroom, 3-bathroom villa in a peaceful suburban neighborhood... ",
    short_description: "Coastal Escapes - Where Waves Beckon",
    bedrooms: 4,
    bathrooms: 3,
    area: 2500,
    price: 550000,
    image_url: "/seaside-villa.png",
  },
  {
    id: "3958dc9e-742f-4377-85e9-fec4b6a6442a",
    type: "Villa",
    name: "Metropolitan Haven",
    href: "/properties/metropolitan-haven",
    description:
      "A chic and fully-furnished 2-bedroom apartment with panoramic city views... ",
    short_description: "Urban Oasis - Life in the Heart of the City",
    bedrooms: 2,
    bathrooms: 2,
    area: 2000,
    price: 550000,
    image_url: "/metropolitan.png",
  },
  {
    id: "3958dc9e-737f-4377-85e9-fec4b6a6442a",
    type: "Villa",
    name: "Rustic Retreat Cottage",
    href: "/properties/rustic-retreat-cottage",
    description:
      "An elegant 3-bedroom, 2.5-bathroom townhouse in a gated community... ",
    short_description: "Countryside Charm - Escape to Nature's Embrace",
    bedrooms: 3,
    bathrooms: 3,
    area: 3000,
    price: 550000,
    image_url: "/rustic-cottage.png",
  },
  {
    id: "50ca3e18-62cd-11ee-8c99-0242ac120002",
    type: "Villa",
    name: "Seaside Serenity Villa",
    href: "/properties/seaside-serenity-villa",
    description:
      "A stunning 4-bedroom, 3-bathroom villa in a peaceful suburban neighborhood... ",
    short_description: "Coastal Escapes - Where Waves Beckon",
    bedrooms: 4,
    bathrooms: 3,
    area: 2500,
    price: 550000,
    image_url: "/seaside-villa.png",
  },
  {
    id: "3958dc9e-787f-4377-85e9-fec4b6a6442a",
    type: "Villa",
    name: "Metropolitan Haven",
    href: "/properties/metropolitan-haven",
    description:
      "A chic and fully-furnished 2-bedroom apartment with panoramic city views... ",
    short_description: "Urban Oasis - Life in the Heart of the City",
    bedrooms: 2,
    bathrooms: 2,
    area: 2000,
    price: 550000,
    image_url: "/metropolitan.png",
  },
  {
    id: "76d65c26-f784-44a2-ac19-586678f7c2f2",
    type: "Villa",
    name: "Rustic Retreat Cottage",
    href: "/properties/rustic-retreat-cottage",
    description:
      "An elegant 3-bedroom, 2.5-bathroom townhouse in a gated community... ",
    short_description: "Countryside Charm - Escape to Nature's Embrace",
    bedrooms: 3,
    bathrooms: 3,
    area: 3000,
    price: 550000,
    image_url: "/rustic-cottage.png",
  },
  {
    id: "d6e15727-9fe1-4961-8c5b-ea44a9bd81aa",
    type: "Villa",
    name: "Seaside Serenity Villa",
    href: "/properties/seaside-serenity-villa",
    description:
      "A stunning 4-bedroom, 3-bathroom villa in a peaceful suburban neighborhood... ",
    short_description: "Coastal Escapes - Where Waves Beckon",
    bedrooms: 4,
    bathrooms: 3,
    area: 2500,
    price: 550000,
    image_url: "/seaside-villa.png",
  },
  {
    id: "126eed9c-c90c-4ef6-a4a8-fcf7408d3c66",
    type: "Villa",
    name: "Metropolitan Haven",
    href: "/properties/metropolitan-haven",
    description:
      "A chic and fully-furnished 2-bedroom apartment with panoramic city views... ",
    short_description: "Urban Oasis - Life in the Heart of the City",
    bedrooms: 2,
    bathrooms: 2,
    area: 2000,
    price: 550000,
    image_url: "/metropolitan.png",
  },
  {
    id: "CC27C14A-0ACF-4F4A-A6C9-D45682C144B9",
    type: "Villa",
    name: "Rustic Retreat Cottage",
    href: "/properties/rustic-retreat-cottage",
    description:
      "An elegant 3-bedroom, 2.5-bathroom townhouse in a gated community... ",
    short_description: "Countryside Charm - Escape to Nature's Embrace",
    bedrooms: 3,
    bathrooms: 3,
    area: 3000,
    price: 550000,
    image_url: "/rustic-cottage.png",
  },
  {
    id: "13D07535-C59E-4157-A011-F8D2EF4E0CBB",
    type: "Villa",
    name: "Seaside Serenity Villa",
    href: "/properties/seaside-serenity-villa",
    description:
      "A stunning 4-bedroom, 3-bathroom villa in a peaceful suburban neighborhood... ",
    short_description: "Coastal Escapes - Where Waves Beckon",
    bedrooms: 4,
    bathrooms: 3,
    area: 2500,
    price: 550000,
    image_url: "/seaside-villa.png",
  },
  {
    id: "410544b2-4001-4271-9855-fec4b6a6442a",
    type: "Villa",
    name: "Metropolitan Haven",
    href: "/properties/metropolitan-haven",
    description:
      "A chic and fully-furnished 2-bedroom apartment with panoramic city views... ",
    short_description: "Urban Oasis - Life in the Heart of the City",
    bedrooms: 2,
    bathrooms: 2,
    area: 2000,
    price: 550000,
    image_url: "/metropolitan.png",
  },
  {
    id: "410544b2-4001-4271-9855-fec4b6a6442b",
    type: "Villa",
    name: "Rustic Retreat Cottage",
    href: "/properties/rustic-retreat-cottage",
    description:
      "An elegant 3-bedroom, 2.5-bathroom townhouse in a gated community... ",
    short_description: "Countryside Charm - Escape to Nature's Embrace",
    bedrooms: 3,
    bathrooms: 3,
    area: 3000,
    price: 550000,
    image_url: "/rustic-cottage.png",
  },
];

const people = [
  {
    id: "88d6cfc6-f27f-469b-8c71-2da012ea03db",
    name: "Max Mitchell",
    role: "Founder",
    profile: "furni",
    image_url: "/avatar1.png",
  },
  {
    id: "44afbc43-1d43-430e-9331-4283ded704c3",
    name: "Sarah Johnson",
    role: "Chief Real Estate Officer",
    profile: "furni",
    image_url: "/avatar2.png",
  },
  {
    id: "25daa00d-a29b-4205-845f-ac2de338db37",
    name: "David Brown",
    role: "Head of Property Management",
    profile: "furni",
    image_url: "/avatar3.png",
  },
  {
    id: "47c95e88-8a7e-4c70-8771-409b526fe386",
    name: "Michael Turner",
    role: "Legal Counsel",
    profile: "furni",
    image_url: "/avatar4.png",
  },
];

const clientsList = [
  {
    id: "83653352-28a4-4f86-a578-7a3b5bb0a556",
    cld: "2019",
    name: "ABC Corporation",
    href: "https://somesite.net/",
    domain: "Commercial Real Estate",
    category: "Luxury Home Development",
    description: `Estatein's expertise in finding the perfect office space for our expanding operations was invaluable. They truly understand our business needs.`,
  },
  {
    id: "3062a3a2-6205-47dc-bcca-db9664ce00a7",
    cld: "2018",
    name: "GreenTech Enterprises",
    href: "https://somesite.net/",
    domain: "Commercial Real Estate",
    category: "Retail Space",
    description: `Estatein's ability to identify prime retail locations helped us expand our brand presence. They are a trusted partner in our growth.`,
  },
  {
    id: "cd036c8f-a5c5-442f-9064-80cbeaad75e4",
    cld: "2019",
    name: "ABC Corporation",
    href: "https://somesite.net/",
    domain: "Commercial Real Estate",
    category: "Luxury Home Development",
    description: `Estatein's expertise in finding the perfect office space for our expanding operations was invaluable. They truly understand our business needs.`,
  },
  {
    id: "3a997c48-6820-41b5-83a0-351ff2588ef6",
    cld: "2018",
    name: "GreenTech Enterprises",
    href: "https://somesite.net/",
    domain: "Commercial Real Estate",
    category: "Retail Space",
    description: `Estatein's ability to identify prime retail locations helped us expand our brand presence. They are a trusted partner in our growth.`,
  },
  {
    id: "b9c397f5-1ae2-46d6-9896-9451db6b526e",
    cld: "2019",
    name: "ABC Corporation",
    href: "https://somesite.net/",
    domain: "Commercial Real Estate",
    category: "Luxury Home Development",
    description: `Estatein's expertise in finding the perfect office space for our expanding operations was invaluable. They truly understand our business needs.`,
  },
  {
    id: "a44bf1c8-6295-4909-bbc8-2802cde4c856",
    cld: "2018",
    name: "GreenTech Enterprises",
    href: "https://somesite.net/",
    domain: "Commercial Real Estate",
    category: "Retail Space",
    description: `Estatein's ability to identify prime retail locations helped us expand our brand presence. They are a trusted partner in our growth.`,
  },
  {
    id: "fb48ff28-9f6c-49b4-95e6-9d479bacba52",
    cld: "2019",
    name: "ABC Corporation",
    href: "https://somesite.net/",
    domain: "Commercial Real Estate",
    category: "Luxury Home Development",
    description: `Estatein's expertise in finding the perfect office space for our expanding operations was invaluable. They truly understand our business needs.`,
  },
  {
    id: "efbdceb4-5854-4dca-8c86-83d3612a0acb",
    cld: "2018",
    name: "GreenTech Enterprises",
    href: "https://somesite.net/",
    domain: "Commercial Real Estate",
    category: "Retail Space",
    description: `Estatein's ability to identify prime retail locations helped us expand our brand presence. They are a trusted partner in our growth.`,
  },
  {
    id: "ffd2b088-da0d-4499-a707-f5893ffbf694",
    cld: "2019",
    name: "ABC Corporation",
    href: "https://somesite.net/",
    domain: "Commercial Real Estate",
    category: "Luxury Home Development",
    description: `Estatein's expertise in finding the perfect office space for our expanding operations was invaluable. They truly understand our business needs.`,
  },
  {
    id: "6ea22a2e-abff-4dae-89c6-0a70c7b7d119",
    cld: "2018",
    name: "GreenTech Enterprises",
    href: "https://somesite.net/",
    domain: "Commercial Real Estate",
    category: "Retail Space",
    description: `Estatein's ability to identify prime retail locations helped us expand our brand presence. They are a trusted partner in our growth.`,
  },
  {
    id: "c5c42e67-e358-49b7-b8fb-78b7629aed3d",
    cld: "2019",
    name: "ABC Corporation",
    href: "https://somesite.net/",
    domain: "Commercial Real Estate",
    category: "Luxury Home Development",
    description: `Estatein's expertise in finding the perfect office space for our expanding operations was invaluable. They truly understand our business needs.`,
  },
  {
    id: "6ec2c216-7498-46a4-af9d-78d367d34f70",
    cld: "2018",
    name: "GreenTech Enterprises",
    href: "https://somesite.net/",
    domain: "Commercial Real Estate",
    category: "Retail Space",
    description: `Estatein's ability to identify prime retail locations helped us expand our brand presence. They are a trusted partner in our growth.`,
  },
];

module.exports = {
  properties,
  people,
  clientsList,
};
